version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/medical
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=medical

networks:
  springmysql-net: